# This workflow will build an Arch Linux ISO file with the commit on it
name: build parchiso per release
on:
  release:
    types:
      - created

env:
  api_key: ${{ secrets.GITHUB_TOKEN }}
  name: ${{ github.event.repository.name }}
  release_name: ${{ github.ref_name }}
  email: ${{ secrets.EMAIL }}
  password: ${{ secrets.PASSWORD }}
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Install Packages via Pacman
        run: pacman -Sy; pacman --noconfirm -S git archiso python python-pip python-pygithub reflector
      - name: install pip pkg
        run: pip install mega.py  --break-system-packages
     # - name: Build image
      #  run: mkarchiso -v iso/
      - name: Upload iso to the release
        run: python tools/upload_asset.py

